spring.application.name=API
# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/farmacia
spring.datasource.username=postgres
spring.datasource.password=enano123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opciones:
# create       ? borra y crea tablas cada vez
# create-drop  ? crea y borra al cerrar
# update       ? actualiza sin borrar datos (recomendado para desarrollo)
# validate     ? solo valida estructura
# none         ? no hace nada
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN DE FECHAS
# ===============================

# ===============================
# LOGS (opcional pero útil)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
